### PR TITLE
Google map extra fields

### PR DESCRIPTION
**Pull request by zeroiszero**
Google Maps JavaScript API: 
- change 'ver' to 'v', value to 'weekly' <https://developers.google.com/maps/documentation/javascript/versions>

Google map extra fields:
- city
- city_alt ( or `administrative_area_level_1` indicates a first-order civil entity below the country level <https://developers.google.com/maps/documentation/geocoding/intro>)
- country
- country_code (two letter ISO 3166-1 country code)

Minified `assets/js/acf-input.js`
- `assets/js/acf-input.min.js`

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi there

Thanks for the PR and discussion.
The idea behind your code is great! 

I have for a long time wanted to extend the Google Maps field and allow developers to save more data from the API.

The last time I looked into this, I decided the best solution for all devs would be to add a JS filter which would specify the data, and a callback on how to get that data. This way, the possibilities would be limitless.

I'm aware that the Google Maps API returns different data when searching vs draging the marker. Did you experience this issue as well? What was your solution?

I'm not sure I will merge in this PR, but this is a good prompt for me to look into the JS filter idea again. I would love to hear your thoughts on the matter. Perhaps we can work together to shape this new feature?

**Comment by zeroiszero** [comment]
Hi, @elliotcondon 
since you prefer the flexible way, could we add something like this:
Screenshot 2019-09-18 at 5 30 05 PM

allow user to specify the fields name and how they want to extract the results from Google Map Javascript AP, in the javascript snippet. require `acf.addFilter` and `acf.applyFilters`.

Yes, Google Maps Javascript API returns different data:
- autocomplete results selected, return [Place Result](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult) via `getPlace()`.
- the rest (dragging the marker/select on map/raw address search), return [Geocoding results](https://developers.google.com/maps/documentation/javascript/geocoding).

**Comment by elliotcondon** [comment]
Thanks for the reply.

I don't think we should encourage users to enter JS into the field settings for XSS reasons.

That said, I do like the idea of adding a setting that allows developers to select which "data pieces" they would like to save. Perhaps we could use a multi-select with the most common data such as "city", "country", etc.

As for the filter, there may be a few ways to go about this, but my first thought is to allow the value to be modified by providing the googleObject (place or geocoding data) like so:
```
acf.add_filter('google_map_value', function( value, googleObject, field ){
	
	// Append city to object.
	value.city = googleObject.address.city;
	
	// Return value
	return value;
});
```

**Comment by zeroiszero** [comment]
> As for the filter, there may be a few ways to go about this, but my first thought is to allow the value to be modified by providing the googleObject (place or geocoding data) like so:

do you mean we internally process the data  (place or geocoding data)  to become a googleObject in JS, then pass to a ACF Filter that return the actual data to be saved based on the multi-select ?

**Comment by elliotcondon** [comment]
Hi @zeroiszero 

The multi-select and JS filter are two separate ideas.

**Idea 1: Field Setting**
ACF could provide a new field setting in the form of a multi-select dropdown where the developer can select from a list of "common" data pieces such as "city", "country". The logic behind this would be part of ACF core and would allow the developer to save more than just the "lat", "lng" and "address" pieces.

**Idea 2: JS filter**
Each time the Google Map field value is changed (when searching for an address, or moving the marker), ACF loads the "lat", "lng" and "address" data from the provided Google Map API object (place or geocoding data).
ACF could provide a filter that allows developers to hook in and append extra data pieces by reading them from the provided Google Map API object.

**Comment by zeroiszero** [comment]
Got it now. Thanks!

**Comment by zeroiszero** [comment]
@elliotcondon Added the JS filter `google_map_results`.

sample filter callback that return object of extra fields:
```
acf.addFilter('google_map_results', function (results) {
	// extract more info: city, region, and country
	var result = results[0];
	var country = null, countryCode = null, city = null, cityAlt = null;
	var c, component;

	for (c = 0; c < result.address_components.length; c += 1) {
		component = result.address_components[c];

		if (component.types[0] === 'locality') {
			city = component.long_name;
			break;
		}
	}
	for (c = 0; c < result.address_components.length; c += 1) {
		component = result.address_components[c];

		if (component.types[0] === 'administrative_area_level_1') {
			cityAlt = component.long_name;
			break;
		}
	}
	for (c = 0; c < result.address_components.length; c += 1) {
		component = result.address_components[c];

		if (component.types[0] === 'country') {
			country = result.address_components[c].long_name;
			countryCode = result.address_components[c].short_name;
			break;
		}
	}

	return {
		city: city,
		city_alt: cityAlt,
		country: country,
		country_code: countryCode
	}
});
```

**Comment by elliotcondon** [comment]
Hi @zeroiszero 

Thanks for the reply.

I don't think I'm ready for a PR on this feature request just yet, but will continue to investigate the JS filter idea further over the next few versions :)

**Comment by zeroiszero** [comment]
Noted with thanks. Will close this thread.

**Pull request closed without merging**
