### PR TITLE
Added loading="lazy" to file icon and file images

### PR DESCRIPTION
**Pull request by g-kanoufi**
Adding the new native lazy loading for file icons and file images as it can take a lot of times if there are many items

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @g-kanoufi 

Thanks for the PR. Adding in the `loading` attribute is a great idea!
I'll need to perform some testing before merging this in, as I have a feeling the missing "width" and "height" attributes may then interfere with some other JS logic that calculates/modifies the DOM.

If the width and height attributes are needed, perhaps this is also a good time to change the hardcoded `<img` HTML to a more WP friendly function such as `wp_get_attachment_image()`.

**Comment by g-kanoufi** [comment]
Hi Elliot,

You are right, i wanted to add this as we have an install were cpt can get up to 500 imgs or files and we are using the img thumb as icons, this make the page loading pretty long, so it seems to me that this simple update could save us a couple of seconds there.

Replacing hard coded img tag with wp_get_attachment_image() sounds like the best options of course, should i update my PR?
It seems width and height are not mandatory but help reduce browser reflow.

Let me know what you think, i'll be happy to update my PR.

I also wanted to add that to the gallery img tag, but not sure how to contribute to the pro addons.

Thank you,


--
Guillaume Kanoufi

**Comment by elliotcondon** [comment]
Thanks @g-kanoufi. No need to update the PR. I've got this on my to-do and will look into this in the new year :)

**Comment by g-kanoufi** [comment]
Awesome, happy holiday to you.

Cheers,

--
Guillaume Kanoufi

**Comment by BlackStar1991** [comment]
Will you implement this fitcha ?

**Comment by g-kanoufi** [comment]
Hi @BlackStar1991, i think this is part of ACF now, if not, not sure that this PR will ever be merged as ACF changed a lot since 2019 and is now property of WPEngine.
I am thus closing this PR.

**Pull request closed without merging**
