### PR TITLE
Rank Math Compatibility

### PR DESCRIPTION
**Pull request by MyThemeShop**
This PR adds deeper compatibility of the Rank Math SEO plugin into ACF so all the text fields created using ACF could be read by the Rank Math plugin.

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @MyThemeShop 

Thanks for the PR. Elliot here, ACF dev.

I don't feel comfortable merging in this much JS into our plugin. Perhaps the compatibility layer can be added within the "Rank Math" plugin instead?

**Comment by MyThemeShop** [comment]
Hello @elliotcondon 

Thank you for your message.

Since we are utilizing ACF's functions to get and process the content, we believe it makes sense to have the compatibility code in the ACF plugin.

Please let us know if that makes sense to you as well.

P.S. We crossed 80,000 active installs today in just under 9 months after launching.

**Comment by elliotcondon** [comment]
Hi @MyThemeShop 

Congrats on your plugin growth :)

However, I disagree that this code should live in the ACF plugin.
This PR contains too much custom JS that I do not wish to maintain or take responsibility of.

Thanks for understanding.

**Comment by MyThemeShop** [comment]
Hello @elliotcondon 

Sure. We can understand and appreciate your patience and follow-ups.

Closing the PR and we will see how we can integrate it in our plugin. Will let you know when we add the compatibility.

Thanks again.

**Pull request closed without merging**
