### PR TITLE
Extend local-json.php to save/delete to multiple concurrent local JSON paths

### PR DESCRIPTION
**Pull request by d12r-dev**
This modification extends the saving and deleting of JSON files to multiple locations:

- extends saving and deleting JSON files from a singular directory to multiple directories
- saves to and deletes the JSON file the respective group has been loaded from
- extends default JSON directories from "acf-json" in child theme to "acf-json" in child and (in second rank) parent theme
- extends "save_json" filter to accept an array of directories, analoguous to the "load_json" filter
- defaults save_json directories to load_json directories, presenting the array to the "save_json" filter
- keeps complete backward compability with current documented behaviour

### CODE REVIEW

**Comment by d12r-dev** [comment]
Rationale for this modification:

ACF already comes with a facility to load JSON files from multiple locations. Currently, this defaults to the "acf-json" directory in the (child) theme and can be extended by pushing onto or replacing an array of directories via the "load_json" filter. There is, however, no provision in ACF to save or delete JSON files from where it loaded them -- it will only ever save or delete JSON files in one singular location. The "save_json" filter currently only accepts a singular directory.

This brings several disadvantages when modifying custom fields in development. It is possible to end up with duplicate, diverging JSON files or JSON files that end up in a different directory than intended. This is especially annoying if custom field groups are used in parent and child themes, or between themes and plugins, one has to manually keep track of changed JSON files and move them after saving.

This modification rectifies this shortcoming. It extends the saving and deleting function to be able to work not only with a singular location but an array of locations supplied using the "load_json" and, if so desired, the "save_json" filters. It keeps backwards compability by accepting a singular location via both filters. And it now by default populates the locations array with the "acf-json" directory in the child theme, and in second rank in the parent theme if present.

While it is not a huge modification, I am aware it might be a disruptive one, so I took great care not to break the behaviour if the "load_json" and "save_json" are used as currently documented.

**Comment by polevaultweb** [comment]
Hey @d12r-dev thanks for submitting the code, I'll get this looked over by the devs when we've got ACF 5.12 out the door.

**Comment by d12r-dev** [comment]
I updated my patch, fixing saving of a new JSON file if the first path in the array is not writable or does not exist.

**Comment by lgladdy** [comment]
Hey @d12r-dev,

Thanks for raising this. We've got this raised an in internal issue to review your code to include in a future release, likely in the next release or two.

Various WordPress changes have forced us to focus on more critical issues over the last few weeks and have bumped this back in the queue, and we suspect this change will require some further changes from our side, along with a significant amount of testing which is why we haven't just rolled it in yet - but we will get to this over the next few months and let you know once we have, or if we find any other issues we need to think about in your proposed solution.

Thanks for your patience!

**Comment by wp-cms** [comment]
Hi, @d12r-dev - this is a much needed improvement. I'm taking it for WP-CMS, the WordPress fork focused towards developers. Works like a charm, thanks for sharing it!

**Comment by shoelaced** [comment]
Is there any movement on this? I'm developing several plugins for use on private client sites that each have an `acf-json` directory with separate sets of field groups packaged with them, and it would be _extremely_ helpful if ACF would just save the JSON back to the respective load point it came from.

**Comment by d12r-dev** [comment]
Superseded by PR #806

**Pull request closed without merging**
