### PR TITLE
Update acf-pt_BR.po

### PR DESCRIPTION
**Pull request by wiliamjk**
Hello! My name is Wiliam and I am a General Translation Editor for Portuguese (Brazil) in the WordPress community. I fully translated the free ACF on translate.wordpress.com and took the time to review, update and correct the ACF PRO translation as well. Now I am proposing an update of the file for the next update.

### CODE REVIEW

**Comment by lgladdy** [comment]
Thanks so much @williamjk! We really appreciate your time in translating ACF.

We'll absolutely get this shipped in our next update, where we'll also pull in all your free translations from translate.wordpress.org too.

Thanks again for helping make ACF better!

**Comment by lgladdy** [comment]
Hey @wiliamjk,

I've merged your changed upstream. I noticed that this PRO `.po` file hadn't been updated from the `acf.pot` though, so there were a bunch of duplicate/missing/updated translations for ACF PRO 6.1.4.

I've attached the updated `.po` here with your changes, so if you want to also translate the new or updated things in here, feel free to do so and update the PR and we'll merge those in too!

Cheers,
Liam

[acf-pt_BR.po.zip](https://github.com/AdvancedCustomFields/acf/files/11233256/acf-pt_BR.po.zip)

**Comment by wiliamjk** [comment]
Oh, I see... 
Sorry for the confusion, I don't know much about the technical part 😅

I translated the file you sent, can I attach it here?
[acf-pt_BR.zip](https://github.com/AdvancedCustomFields/acf/files/11237155/acf-pt_BR.zip)

**Comment by lgladdy** [comment]
Hey @wiliamjk,

All good! I realised we don't actually give instructions on how to update the file for new translators anywhere, so I'll get that updated!

But, your translated file is perfect anyway! I won't merge it here, as it's already merged in our private repo which updates here on each release, so you'll see these changes in ACF 6.1.5 in the next few weeks!

Thanks again
Liam

**Pull request closed without merging**
