### PR TITLE
Dynamic size for multi selects

### PR DESCRIPTION
**Pull request by fiskhandlarn**
Set multi select size to size attribute or default to nr of choices.

Issue: size was hardcoded to 5.

### CODE REVIEW

**Comment by elliotcondon** [comment]
Hi @fiskhandlarn 

Thanks for the PR. I like the idea, but do not want to force all existing select fields to their max height. Instead of the code change, are you able to make use of CSS to change the height?
This may not be as 'dynamic' but could solve the issue for now.

**Comment by fiskhandlarn** [comment]
@elliotcondon I would really like for the field to at least be able to receive the attribute `size`. Should I make a new PR for this (without the auto sizing by nr of items)?

**Comment by elliotcondon** [comment]
Hi @fiskhandlarn 

Hold off on the PR. I like the idea and will add it to my to-do list.

Similar to your code, I will look for a $field['size'] setting, and if found, will add this to the select element. I will also check if this setting === 'auto' and if so, calculate the size based off the number of choices.

Thanks again for the feature request. I will close this for now and hope to add this into an update soon.

**Comment by fiskhandlarn** [comment]
@elliotcondon Sounds good! I like the 'auto' idea. 

When do you think this will implemented/released? :) I could make a new PR with the features you're describing if that would help?

**Comment by elliotcondon** [comment]
Hi @fiskhandlarn 

No need for a PR. I will work on this alongside other feature requests.

**Comment by fiskhandlarn** [comment]
@elliotcondon I noticed this is still an issue in version 5.6.10. Any thoughts on when this will be fixed? I'm ready to send a PR if that would help.

**Comment by elliotcondon** [comment]
Hi @fiskhandlarn 

Thanks for the reminder. I've been distracted (and very busy) working on Gutenberg compatibility and ACF PRO 5.7.

It's a busy time at at the moment and appreciate your patience.
This feature is on my list, along with many others.

**Comment by fiskhandlarn** [comment]
@elliotcondon Fully understandable, Gutenberg compability sounds like a behemoth to implement. X) Thanks for the info! Let me know if I can do anything to help.

**Pull request closed without merging**
